[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable Solidity and Huff
ffi = true
evm_version = "shanghai"

remapping = ['foundry-huff/=lib/foundry-huff/src']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
